language: objective-c

os:
  - osx
osx_image:
  - xcode10.2
  - xcode11.3
  - xcode12.2
env:
  - PLATFORM=SIMULATOR DEPLOYMENT_TARGET=11.0
  - PLATFORM=SIMULATOR64 DEPLOYMENT_TARGET=11.0
  - PLATFORM=OS DEPLOYMENT_TARGET=11.0
  - PLATFORM=OS BUILD_SHARED=1 DEPLOYMENT_TARGET=11.0
  - PLATFORM=OS64 DEPLOYMENT_TARGET=11.0
  - PLATFORM=OS64 BUILD_SHARED=1 DEPLOYMENT_TARGET=11.0
  - PLATFORM=TVOS DEPLOYMENT_TARGET=11.0
  - PLATFORM=WATCHOS DEPLOYMENT_TARGET=5.0
  - PLATFORM=OS64COMBINED USE_XCODE=1 DEPLOYMENT_TARGET=11.0
  - PLATFORM=MAC DEPLOYMENT_TARGET=10.13
  - PLATFORM=OS64COMBINED USE_XCODE=1 DEPLOYMENT_TARGET=11.0 BUILD_CURL=1

install: skip

script:
  - ./.travis/build.sh
